server:
  port: 10324

# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.jzy.gaisagroup.model
  mapper-locations: classpath:mybatis/mapper/**/*.xml

# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: "false"
  row-bounds-with-count: "true"
  offset-as-page-num: "true"

# 日志输出
logging:
  level:
    com.jzy.kaisagroup.mapper: debug

# 数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.52.248.231:10224/Test?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xiaochang0324
    platform: mysql
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    logSlowSql: true



